version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: doctors_directory
      MYSQL_USER: doctor
      MYSQL_PASSWORD: doctor
      MYSQL_ROOT_PASSWORD: doctor
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  meilisearch:
    image: getmeili/meilisearch:v1.11
    restart: unless-stopped
    ports:
      - '7700:7700'
    environment:
      MEILI_ENV: development

volumes:
  mysql-data:
